### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Maniues** [Dot-Stuff/Dot-Server#1]
Add the license.
Suggestions:
- Schema (what others can do)
- MIT (do anything, but credit authors)
- Apache (the same as MIT, but add patent clause)
- BSD [2,3 clause] (One of the most popular licenses, 2Clause version is the same as MIT, 3Clause version is the same as MIT X11 license: you cannot use the names of the contributors to promote modified version; 2Clause recommended)
- GNU GPL [2/3] (Do anything, but if you distribute code/binaries, you must license all the code under GPL - you cannot change the license and you must distribute source code) [GPLv2 is old but still good, GPLv3 preffered]
- GNU AGPL [v2,v3] (The same as GPL, but if you allow others to interact with the software via the web without offering code or binaries to download, you must also distribute the source code)
# For the code related to "Friday Night Funkin' " I recommend using Apache license or eventually GPLv3.
## If you choose GPL, please use GPL version *3*, because version 2 is not compatible with Apache License

**Comment by DotWith** [comment]
Ok, I've applied GPL v3
