### ISSUE TITLE
thanks for the code

### ISSUE THREAD

**Issue by Jotaro-Gaming** [Dot-Stuff/Dot-Server#2]
I'm stealing it :trollface:

**Comment by DotWith** [comment]
You are stealing my code? Then I must call the police, fbi and cia.

**Comment by MrClogsworthYT** [comment]
> You are stealing my code? Then I must call the police, fbi and cia.

bum bum bum bum bum bum bum bum
(amogus saved me :trollface:

**Comment by MrClogsworthYT** [comment]
invite me to ur oranization or amogus kill u @DotWith

**Comment by MrClogsworthYT** [comment]
you have 1 hour
